// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomNav: typeof import('./components/BottomNav.vue')['default']
    copy: typeof import('./components/Counter copy.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DescAfterLogo: typeof import('./components/DescAfterLogo.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HomeList: typeof import('./components/HomeList.vue')['default']
    LogoUtama: typeof import('./components/LogoUtama.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
